# Generated by Django 3.0.2 on 2020-02-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0021_auto_20200218_0920'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='wishlist.WishItem'),
        ),
    ]
