# Generated by Django 3.0.2 on 2020-02-18 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Your name')),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Your cell phone number')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Which city are you in?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
