# Generated by Django 3.0.2 on 2020-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200223_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='What is your address'),
        ),
    ]
