# Generated by Django 3.0.2 on 2020-02-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
