# Generated by Django 3.0.2 on 2020-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your name')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Your email')),
                ('phone', models.IntegerField(verbose_name='Your cell phone number')),
                ('city', models.CharField(max_length=30, verbose_name='Which city are you in?')),
                ('item_description', models.TextField(verbose_name='Describe the item briefly')),
                ('item_image1', models.ImageField(upload_to='vip_order', verbose_name='Upload a photo of the item')),
                ('item_image2', models.ImageField(null=True, upload_to='vip_order', verbose_name='Upload another photo of the item')),
                ('item_image3', models.ImageField(null=True, upload_to='vip_order', verbose_name='Upload another photo of the item')),
                ('slug', models.SlugField(default='', editable=False, max_length=20)),
            ],
        ),
    ]
