# Generated by Django 3.0.2 on 2020-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viporder',
            name='item_image2',
            field=models.ImageField(blank=True, null=True, upload_to='vip_order', verbose_name='Upload another photo of the item'),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='item_image3',
            field=models.ImageField(blank=True, null=True, upload_to='vip_order', verbose_name='Upload another photo of the item'),
        ),
    ]
