# Generated by Django 3.0.2 on 2020-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20200224_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='viporder',
            name='address',
            field=models.CharField(default='None', max_length=30, verbose_name='What is your address?'),
            preserve_default=False,
        ),
    ]
