# Generated by Django 3.0.2 on 2020-02-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0005_remove_viporder_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viporder',
            name='slug',
        ),
    ]
