# Generated by Django 3.0.2 on 2020-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0006_remove_viporder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viporder',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Your email'),
        ),
    ]
