# Generated by Django 3.0.2 on 2020-02-26 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0007_auto_20200226_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viporder',
            options={'ordering': ['-date_created'], 'verbose_name': 'VIP Order', 'verbose_name_plural': 'VIP Orders'},
        ),
        migrations.AddField(
            model_name='viporder',
            name='active',
            field=models.BooleanField(default=False, verbose_name='VIP Order Active?'),
        ),
        migrations.AddField(
            model_name='viporder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
