# Generated by Django 3.0.2 on 2020-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0008_auto_20200226_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='viporder',
            name='ref_number',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='VIP Order Number'),
        ),
    ]
