# Generated by Django 3.0.2 on 2020-02-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0009_viporder_ref_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viporder',
            options={'ordering': ['-active', '-date_created'], 'verbose_name': 'VIP Order', 'verbose_name_plural': 'VIP Orders'},
        ),
    ]
