# Generated by Django 3.0.2 on 2020-02-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Categories'},
        ),
    ]
