# Generated by Django 3.0.2 on 2020-02-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='men',
        ),
        migrations.RemoveField(
            model_name='category',
            name='women',
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Women'), (2, 'Men')], default=2),
        ),
    ]
