# Generated by Django 3.0.2 on 2020-02-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20200207_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='men',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='women',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
