# Generated by Django 3.0.2 on 2020-02-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20200203_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Category', 'verbose_name_plural': 'Sub-Categories'},
        ),
    ]
