# Generated by Django 3.0.2 on 2020-02-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20200207_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Women'), (2, 'Men')], default=1),
        ),
    ]
