# Generated by Django 3.0.2 on 2020-02-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_auto_20200203_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
