# Generated by Django 3.0.2 on 2020-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_auto_20200203_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
