# Generated by Django 3.0.2 on 2020-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_auto_20200207_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='index_carousel_images')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default='0'),
        ),
    ]
