# Generated by Django 3.0.2 on 2020-02-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_auto_20200203_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image_1',
        ),
    ]
