# Generated by Django 3.0.2 on 2020-02-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_auto_20200209_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_discount_percentage', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_tagged',
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boutique.Tag'),
        ),
    ]
