# Generated by Django 3.0.2 on 2020-02-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_auto_20200210_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slogan',
            field=models.CharField(default='Purchase NOW for the extra <django.db.models.fields.IntegerField>% off!', max_length=200),
        ),
    ]
