# Generated by Django 3.0.2 on 2020-02-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_remove_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
