# Generated by Django 3.0.2 on 2020-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_tag_slogan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
