# Generated by Django 3.0.2 on 2020-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
