# Generated by Django 3.0.2 on 2020-02-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_auto_20200203_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
