# Generated by Django 3.0.2 on 2020-02-10 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_auto_20200210_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexcarousel',
            options={'ordering': ['-uploaded_date'], 'verbose_name': 'Index Carousel', 'verbose_name_plural': 'Index Carousels'},
        ),
        migrations.AddField(
            model_name='indexcarousel',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
