# Generated by Django 3.0.2 on 2020-02-10 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_auto_20200210_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
