# Generated by Django 3.0.2 on 2020-02-10 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_auto_20200210_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage'),
        ),
    ]
