# Generated by Django 3.0.2 on 2020-02-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_auto_20200211_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Sub-category', 'verbose_name_plural': 'Sub-categories'},
        ),
    ]
