# Generated by Django 3.0.2 on 2020-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0019_auto_20200212_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-uploaded_date', '-discount_percentage']},
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.IntegerField(choices=[(1, 'women'), (2, 'men')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
