# Generated by Django 3.0.2 on 2020-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0020_auto_20200216_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcarousel',
            name='image',
            field=models.ImageField(upload_to='index_carousel_images', verbose_name='Image (Size: 2100 x 1400 px)'),
        ),
    ]
