# Generated by Django 3.0.2 on 2020-02-23 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0021_auto_20200218_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['gender', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='indexcarousel',
            options={'ordering': ['uploaded_date'], 'verbose_name': 'Index Carousel', 'verbose_name_plural': 'Index Carousels'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Brand Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='indexcarousel',
            name='description',
            field=models.TextField(verbose_name='Carousel Text'),
        ),
        migrations.AlterField(
            model_name='indexcarousel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Carousel Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sub-category Description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sub-category Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan for tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tag (discount percentage)'),
        ),
    ]
