# Generated by Django 3.0.2 on 2020-02-19 05:51

from django.db import migrations, models
import django.db.models.deletion
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_slug'),
        ('boutique', '0021_auto_20200218_0920'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(default='190220-61294', max_length=15)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('ref_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BagItem',
        ),
        migrations.DeleteModel(
            name='ShoppingBag',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shopping.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=models.SET(shopping.models.get_sentinel_user), to='users.Profile'),
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.OrderItem'),
        ),
    ]
