# Generated by Django 3.0.2 on 2020-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200219_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousorder',
            name='ref_number',
            field=models.CharField(default='190220-52720', max_length=15),
        ),
    ]
