# Generated by Django 3.0.2 on 2020-02-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0021_auto_20200218_0920'),
        ('shopping', '0005_auto_20200219_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='My email'),
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='customer_location',
            field=models.CharField(blank=True, max_length=50, verbose_name='My Location'),
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='My name'),
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='customer_phone',
            field=models.IntegerField(null=True, verbose_name='My phone number'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.Item'),
        ),
    ]
