# Generated by Django 3.0.2 on 2020-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200219_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
