# Generated by Django 3.0.2 on 2020-02-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20200219_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousorder',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'Anonymous Order'},
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='customer_email',
            field=models.EmailField(max_length=100, verbose_name='My email'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='customer_location',
            field=models.CharField(max_length=50, verbose_name='My Location'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='My name'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='customer_phone',
            field=models.IntegerField(default=True, verbose_name='My phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='ref_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
