# Generated by Django 3.0.2 on 2020-02-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200220_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousorder',
            options={'ordering': ['-active', '-date_ordered'], 'verbose_name': 'Anonymous Order'},
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Order Active'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Order Active'),
        ),
    ]
