# Generated by Django 3.0.2 on 2020-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20200220_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-active', '-date_ordered'], 'verbose_name': 'Anonymous Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Order Active'),
        ),
    ]
