# Generated by Django 3.0.2 on 2020-02-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20200220_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-is_ordered', '-active', '-date_ordered'], 'verbose_name': 'Registered Order', 'verbose_name_plural': 'Registered Orders'},
        ),
    ]
