# Generated by Django 3.0.2 on 2020-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20200223_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousorder',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Order Active?'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='ref_number',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Order Active?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Reference Number'),
        ),
    ]
